# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mp_archetype',
            fields=[
                ('id1', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('gid', models.UUIDField()),
                ('crtdate', models.DateField()),
                ('crtby', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Mp_element',
            fields=[
                ('fldname', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('fldtype', models.CharField(max_length=64)),
                ('gid', models.UUIDField()),
                ('crtdate', models.DateField()),
                ('crtby', models.UUIDField()),
            ],
        ),
    ]
