# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compobulator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_element',
            name='archetypeid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
