# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compobulator_app', '0002_mp_element_archetypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp_archetype',
            name='crtby',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='mp_archetype',
            name='gid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='mp_element',
            name='crtby',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='mp_element',
            name='gid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
